### ISSUE TITLE
cmd/server: Prometheus metric for last refresh timestamp

### ISSUE THREAD

**Issue by adamdecaf** [moov-io/ofac#47]
OFAC's server should expose a Prometheus gauge for the last unix timestamp that data was successfully refreshed. This can be used with an alert pretty easily. (example below)

```yaml
groups:
 - name: ./ofac.rules
   rules:
    - alert: OFACStaleData
      expr: (now() - ofac_data_last_refresh) < 60*60*12 # 12 hours ago
      for: 1h
      labels:
        severity: warning
      annotations:
        description: "OFAC stale data, last refresh {{ humanizeTimestamp $value }}"
```
